# Generated by Django 4.2.7 on 2024-04-21 13:09

import api_v1.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api_v1.utils.handle_article_photo, verbose_name='Фото')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержимое')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'опубликованно')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api_v1.utils.handle_employee_photo, verbose_name='Фото')),
                ('post', models.CharField(max_length=64, verbose_name='Должность')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('authors', models.CharField(max_length=256, verbose_name='Авторы')),
                ('journal', models.CharField(max_length=256, verbose_name='Журнал')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=api_v1.utils.handle_project_photo, verbose_name='Фото')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_realized', models.BooleanField(choices=[(False, 'Реализовано'), (True, 'разрабатывается')], default=1, verbose_name='Статус')),
                ('type', models.IntegerField(choices=[(0, 'Фото'), (1, 'Видео')], verbose_name='Тип')),
                ('slug', models.SlugField(blank=True, max_length=256, null=True, unique=True, verbose_name='Slug')),
                ('authors', models.ManyToManyField(blank=True, to='api_v1.employee', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
